import os
STATIC_FOLDER = os.getenv('STATIC_FOLDER', os.path.join(os.getcwd(), 'landing'))
DATA_FOLDER = os.getenv('DATA_FOLDER', os.path.join(os.getcwd(), 'data'))
NEWS_FILE = os.getenv('NEWS_FILE', os.path.join(DATA_FOLDER, 'news.jsonl'))
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', 'changeme')
CONTACT_FILE = os.getenv('CONTACT_FILE', os.path.join(DATA_FOLDER, 'contact.jsonl'))
NEWSLETTER_FILE = os.getenv('NEWSLETTER_FILE', os.path.join(DATA_FOLDER, 'newsletter.jsonl'))
ROADMAP_FILE = os.getenv('ROADMAP_FILE', os.path.join(DATA_FOLDER, 'roadmap.jsonl'))
MAIL_SERVER = os.getenv('MAIL_SERVER', 'smtp.gmail.com')
MAIL_PORT = int(os.getenv('MAIL_PORT', 587))
MAIL_USE_TLS = os.getenv('MAIL_USE_TLS', 'true').lower() in ('true', '1', 't')
MAIL_USERNAME = os.getenv('MAIL_USERNAME', 'abc@gmail.com')
MAIL_PASSWORD = os.getenv('MAIL_PASSWORD', 'abcd efgh ijkl mnop')
MAIL_DEFAULT_SENDER = os.getenv('MAIL_DEFAULT_SENDER', MAIL_USERNAME)
MAIL_RECIPIENT = os.getenv('MAIL_RECIPIENT', MAIL_USERNAME)
