site_name: Danish Foundation Models
site_url: https://foundationmodels.dk
use_directory_urls: false

docs_dir: "docs/"
watch: [docs/]

theme:
  name: material
  custom_dir: overrides
  favicon: _static/icon.png
  logo: _static/icon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - pymdownx.caret
    - pymdownx.tilde
  palette:
    primary: white
    accent: custom
    # automatic dark mode is

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - _static/extra.css

copyright: This site made available under a Creative Commons Attribution 4.0 license

nav:
  - About: index.md
  - News: news

plugins:
  - mkdocs-jupyter
  - search
  - blog:
      blog_dir: news

extra: 
  generator: false