# creates the documentation and pushes it to the gh-pages branch
name: Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          python-version: "3.10"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Dependencies
        run: uv sync

      - name: Build MkDocs
        if: github.event_name == 'push'
        run: uv run mkdocs build

      - name: Add .nojekyll
        if: github.event_name == 'push'
        run: |
          mkdir -p site
          touch site/.nojekyll

      - name: Copy landing page
        if: github.event_name == 'push'
        run:
          cp -rv landing/ site/

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages

      - name: Build (PR only)
        if: github.event_name == 'pull_request'
        run: make build-docs
